{{- if .Values.cart.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: {{ include "microshop.namespace" . }}
  labels:
    {{- include "microshop.labels" . | nindent 4 }}
    app: cart
    tier: backend
  annotations:
    chaos.mesh.io/inject: "true"
spec:
  replicas: {{ .Values.cart.replicas }}
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
        tier: backend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      {{- if .Values.cart.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.cart.nodeSelector | nindent 8 }}
      {{- end }}
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
      containers:
        - name: cart
          image: "{{ .Values.cart.image.repository }}:{{ .Values.cart.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: REDIS_URL
              value: "redis://redis:{{ .Values.redis.service.port }}"
          envFrom:
            - configMapRef:
                name: microshop-config
          resources:
            {{- toYaml .Values.cart.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.cart.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.cart.readinessProbe | nindent 12 }}
{{- end }}
