{{- if .Values.catalog.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: {{ include "microshop.namespace" . }}
  labels:
    {{- include "microshop.labels" . | nindent 4 }}
    app: catalog
    tier: backend
spec:
  type: {{ .Values.catalog.service.type }}
  ports:
    - port: {{ .Values.catalog.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: catalog
{{- end }}
