{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: {{ include "microshop.namespace" . }}
  labels:
    {{- include "microshop.labels" . | nindent 4 }}
    app: rabbitmq
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: data
        version: v1
    spec:
      {{- if .Values.rabbitmq.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.rabbitmq.nodeSelector | nindent 8 }}
      {{- end }}
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
      containers:
        - name: rabbitmq
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.rabbitmq.auth.username }}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.rabbitmq.auth.password }}"
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - check_running
            initialDelaySeconds: 20
            periodSeconds: 10
{{- end }}
