{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ include "microshop.namespace" . }}
  labels:
    {{- include "microshop.labels" . | nindent 4 }}
    app: rabbitmq
    tier: data
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: 5672
      protocol: TCP
      name: amqp
    - port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: 15672
      protocol: TCP
      name: management
  selector:
    app: rabbitmq
{{- end }}
