{{- if .Values.checkout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: {{ include "microshop.namespace" . }}
  labels:
    {{- include "microshop.labels" . | nindent 4 }}
    app: checkout
    tier: backend
spec:
  type: {{ .Values.checkout.service.type }}
  ports:
    - port: {{ .Values.checkout.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: checkout
{{- end }}
